version: "3.0"
services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile
    labels:
      traefik.enable: 'true'
      traefik.http.routers.limesurvey-http-router.entrypoints: "http"
      traefik.http.routers.limesurvey-http-router.rule: "PathPrefix(`/limesurvey`)"
      traefik.http.services.limesurvey-service.loadbalancer.server.port: "8080"
    links:
      - lime-db
    depends_on:
      - lime-db
    volumes:
      # Unfortunately the StripPrefix Function in Traefik won't work;
      # Meaning, we will have to set 'Alias /limesurvey "/var/www/html"' in the Apache Config
      - "./examples/apache-example.conf:/etc/apache2/sites-available/000-default.conf:ro"
    environment:
      - "DB_HOST=lime-db"
      # - "DB_PASSWORD="
      # - "ADMIN_PASSWORD="
      - "PUBLIC_URL=http://localhost:8888/limesurvey"
      - "BASE_URL=http://localhost:8888/limesurvey"
  traefik:
    image: docker.io/traefik:v2.9
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:8888"
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  lime-db:
    image: docker.io/mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      # - "MYSQL_PASSWORD="
      # - "MYSQL_ROOT_PASSWORD="
