version: "3.0"
services:
  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_HOST=lime-db"
      # - "DB_PASSWORD="
      # - "ADMIN_PASSWORD="
      - "PUBLIC_URL=http://my.survey.localhost:8080"  # Example, Change this
      - "BASE_URL=http://my.survey.localhost:8080"  # Example, Change this
  proxy:
    image: docker.io/httpd:bullseye
    volumes:
      - "./examples/apache-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "./examples/apache-reverse-proxy.conf:/usr/local/apache2/conf/reverse-proxy.conf:ro"
    ports:
      - "8080:8080"
  lime-db:
    image: docker.io/mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      # - "MYSQL_PASSWORD="
      # - "MYSQL_ROOT_PASSWORD="

