version: "3.0"
services:
  limesurvey:
    build:
      context: 5.0/fpm/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - /tmp/upload/surveys:/var/www/html/upload/surveys
      - lime:/var/www/html
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=secret"
      - "ADMIN_PASSWORD=foobar"
  lime-web:
    image: nginx
    links:
      - limesurvey
    ports:
      - "8080:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
      - lime:/var/www/html
  lime-db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
volumes:
  lime:
